# Generated by Django 5.0.6 on 2024-06-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehandiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
