# Generated by Django 5.0.6 on 2024-06-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehandiApp', '0002_alter_contact_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.BigIntegerField(default=''),
        ),
    ]
